apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "customized-script-remediation.medik8s.io/v1alpha1",
          "kind": "CustomizedScriptRemediation",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "customized-script-remediation",
              "app.kubernetes.io/instance": "customizedscriptremediation-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "customizedscriptremediation",
              "app.kubernetes.io/part-of": "customized-script-remediation"
            },
            "name": "customizedscriptremediation-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "customized-script-remediation.medik8s.io/v1alpha1",
          "kind": "CustomizedScriptRemediationConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "customized-script-remediation",
              "app.kubernetes.io/instance": "customizedscriptremediationconfig-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "customizedscriptremediationconfig",
              "app.kubernetes.io/part-of": "customized-script-remediation"
            },
            "name": "customizedscriptremediationconfig-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "customized-script-remediation.medik8s.io/v1alpha1",
          "kind": "CustomizedScriptRemediationTemplate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "customized-script-remediation",
              "app.kubernetes.io/instance": "customizedscriptremediationtemplate-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "customizedscriptremediationtemplate",
              "app.kubernetes.io/part-of": "customized-script-remediation"
            },
            "name": "customizedscriptremediationtemplate-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: ""
    operators.operatorframework.io/builder: operator-sdk-v1.26.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: customized-script-remediation.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CustomizedScriptRemediationConfig is the Schema for the customizedscriptremediationconfigs
        API
      displayName: Customized Script Remediation Config
      kind: CustomizedScriptRemediationConfig
      name: customizedscriptremediationconfigs.customized-script-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedScriptRemediation is the Schema for the customizedscriptremediations
        API
      displayName: Customized Script Remediation
      kind: CustomizedScriptRemediation
      name: customizedscriptremediations.customized-script-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedScriptRemediationTemplate is the Schema for the customizedscriptremediationtemplates
        API
      displayName: Customized Script Remediation Template
      kind: CustomizedScriptRemediationTemplate
      name: customizedscriptremediationtemplates.customized-script-remediation.medik8s.io
      specDescriptors:
      - description: Template defines the desired state of CustomizedScriptRemediationTemplate
        displayName: Template
        path: template
      version: v1alpha1
  description: TBD
  displayName: Customized Script Remediation Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediationconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediationconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediationconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediations/finalizers
          verbs:
          - update
        - apiGroups:
          - customized-script-remediation.medik8s.io
          resources:
          - customizedscriptremediations/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: customized-script-remediation-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: customized-script-remediation
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: customized-script-remediation
          control-plane: controller-manager
        name: customized-script-remediation-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/mshitrit/customized-script-remediation-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: customized-script-remediation-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: customized-script-remediation-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - remediation
  - auto-healing
  - recovery
  - high-availability
  - baremetal
  - script
  - CSR
  links:
  - name: Customized Script Remediation
    url: https://customized-script-remediation.domain
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  provider:
    name: Medik8s
    url: https://www.medik8s.io/
  version: 0.0.1
