---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-customized-user-remediation-medik8s-io-v1alpha1-customizeduserremediationtemplate
  failurePolicy: Fail
  name: mcustomizeduserremediationtemplate.kb.io
  rules:
  - apiGroups:
    - customized-user-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customizeduserremediationtemplates
  sideEffects: None
