# permissions for end users to edit customizedscriptremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customizedscriptremediation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: customized-user-remediation
    app.kubernetes.io/part-of: customized-user-remediation
    app.kubernetes.io/managed-by: kustomize
  name: customizedscriptremediation-editor-role
rules:
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizedscriptremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizedscriptremediations/status
  verbs:
  - get
