# permissions for end users to view customizedscriptremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customizedscriptremediationtemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: customized-user-remediation
    app.kubernetes.io/part-of: customized-user-remediation
    app.kubernetes.io/managed-by: kustomize
  name: customizedscriptremediationtemplate-viewer-role
rules:
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizedscriptremediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizedscriptremediationtemplates/status
  verbs:
  - get
