---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediationconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediationconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediationconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediations/finalizers
  verbs:
  - update
- apiGroups:
  - customized-user-remediation.medik8s.io
  resources:
  - customizeduserremediations/status
  verbs:
  - get
  - patch
  - update
