apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: OpenShift Optional
    containerImage: ""
    description: Customized User Remediation Operator will remediate unhealthy nodes
      by running a pre defined user script on the unhealthy node. Since the user has
      full control over the script content, is may be quite risky so apply discretion.
    olm.skipRange: '>=0.0.1'
    operatorframework.io/suggested-namespace: openshift-workload-availability
    operatorframework.io/suggested-namespace-template: '{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"openshift-workload-availability","annotations":{"openshift.io/node-selector":""}}}'
    repository: https://github.com/medik8s/customized-user-remediation
    support: Medik8s
  name: customized-user-remediation.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CustomizedUserRemediationConfig is the Schema for the customizeduserremediationconfigs
        API
      displayName: Customized User Remediation Config
      kind: CustomizedUserRemediationConfig
      name: customizeduserremediationconfigs.customized-user-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedUserRemediation is the Schema for the customizeduserremediations
        API
      displayName: Customized User Remediation
      kind: CustomizedUserRemediation
      name: customizeduserremediations.customized-user-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedUserRemediationTemplate is the Schema for the customizeduserremediationtemplates
        API
      displayName: Customized User Remediation Template
      kind: CustomizedUserRemediationTemplate
      name: customizeduserremediationtemplates.customized-user-remediation.medik8s.io
      specDescriptors:
      - description: Template defines the desired state of CustomizedUserRemediationTemplate
        displayName: Template
        path: template
      version: v1alpha1
  description: |
    ### Introduction
    Customized User Remediation (CUR) works with Node Health Check to remediate unhealthy nodes by running a user customized script on the unhealthy node.
    This operator does not preform any fencing on the remediated node so users should be careful with the scripts that are being used.

    ### Compatibility
    CUR is one of the remediator operators by [Medik8s](https://www.medik8s.io/remediation/remediation/),
    such as [Self Node Remediation](https://github.com/medik8s/self-node-remediation), [Fence Agents Remediation](https://github.com/medik8s/fence-agents-remediation)  and [Machine Deletion Remediation](https://github.com/medik8s/machine-deletion-remediation),
    that were designed to run with the Node HealthCheck Operator [(NHC)](https://github.com/medik8s/node-healthcheck-operator) which detects an unhealthy node and creates remediation CR.
    It is recommended to use FAR with NHC for an easier and smoother experience by fully automating the remediation process, but it can be used as a standalone remediator for the more experienced user.

    ### Advantages
    - Flexibility - CUR is quite flexible since it's remediation process is a user-customized script.
  displayName: Customized User Remediation Operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - remediation
  - auto-healing
  - recovery
  - high-availability
  - baremetal
  - script
  - CUR
  - customized-user-remediation
  - Medik8s
  links:
  - name: Customized User Remediation
    url: https://medik8s.io
  - name: Source Code
    url: https://github.com/medik8s/customized-user-remediation
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: Medik8s
    url: https://www.medik8s.io/
  version: 0.0.0
