apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: openshift-workload-availability
    operatorframework.io/suggested-namespace-template: '{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"openshift-workload-availability","annotations":{"openshift.io/node-selector":""}}}'
  name: customized-user-remediation.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CustomizedUserRemediationConfig is the Schema for the CustomizedUserremediationconfigs
        API
      displayName: Customized User Remediation Config
      kind: CustomizedUserRemediationConfig
      name: CustomizedUserremediationconfigs.customized-user-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedUserRemediation is the Schema for the CustomizedUserremediations
        API
      displayName: Customized User Remediation
      kind: CustomizedUserRemediation
      name: CustomizedUserremediations.customized-user-remediation.medik8s.io
      version: v1alpha1
    - description: CustomizedUserRemediationTemplate is the Schema for the CustomizedUserremediationtemplates
        API
      displayName: Customized User Remediation Template
      kind: CustomizedUserRemediationTemplate
      name: CustomizedUserremediationtemplates.customized-user-remediation.medik8s.io
      specDescriptors:
      - description: Template defines the desired state of CustomizedUserRemediationTemplate
        displayName: Template
        path: template
      version: v1alpha1
  description: TBD
  displayName: Customized User Remediation Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - remediation
  - auto-healing
  - recovery
  - high-availability
  - baremetal
  - script
  - CUR
  links:
  - name: Customized User Remediation
    url: https://customized-user-remediation.domain
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: Medik8s
    url: https://www.medik8s.io/
  version: 0.0.0
