## Append samples you want in your CSV to this file as resources ##
resources:
- customized-script-remediation_v1alpha1_customizedscriptremediation.yaml
- customized-script-remediation_v1alpha1_customizedscriptremediationtemplate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
